fix: Remove YouSlider to fix libcolorpicker crash and re-enable YTDiscordRPC-Bypass

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -182,8 +182,6 @@ jobs:
       - name: Clone Alderis
         run: git clone --quiet --depth=1 https://github.com/hbang/Alderis.git
 
-      - name: Clone YouSlider
-        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouSlider.git
 
       - name: Clone YouChooseQuality
         run: git clone --quiet https://github.com/PoomSmart/YouChooseQuality.git
@@ -354,9 +352,9 @@ jobs:
           make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
           mv packages/*.deb ${{ github.workspace }}/imyt.deb
           
-#      - name: Download YTDiscordRPC-Bypass
-#        run: |
-#          wget "https://github.com/puckyking/YTDiscordRPC-Bypass/releases/latest/download/ytdiscordrpc.deb" --quiet --no-verbose -O ytdiscordrpc.deb || echo "Failed to download YTDiscordRPC-Bypass"
+      - name: Download YTDiscordRPC-Bypass
+        run: |
+          wget "https://github.com/puckyking/YTDiscordRPC-Bypass/releases/latest/download/ytdiscordrpc.deb" --quiet --no-verbose -O ytdiscordrpc.deb || echo "Failed to download YTDiscordRPC-Bypass"
 
       - name: Inject Tweaks Into IPA
         run: |
